# Generated by Django 2.1.7 on 2019-03-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PholderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=20)),
                ('pholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permalinks.Pholder')),
            ],
        ),
        migrations.AddField(
            model_name='pholder',
            name='pholder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permalinks.PholderType'),
        ),
    ]
